export default interface InputsInterface {
    power_of_attorney: string,
    full_name: string,
    ocuppation: string,
    nationality: string,
    marital_status: string,
    common_law_marriage: boolean,
    rg: string,
    uf_for_RG_id: number,
    issuing_body_id: number,
    cpf: string,
    email: string,
    mother_name: string,
    cep: string,
    cepNotFound: boolean,
    state_for_address_id: string,
    city_id: string,
    neighborhood_id: string,
    // address_type_id: number,
    address_name: string,
    address_complement_type: string,
    address_complement_name: string,
    ctps_n: string,
    ctps_serie: string,
    uf_for_ctps: string
}