export const API_BASE_URL: string = "https://sistema-rc-e0ef46aabaec.herokuapp.com";

export const BACKEND_DATE_FORMAT: string = 'YYYY-MM-DDTHH:mm:ss.SSSSSS';

export const SYSTEM_PERMISSIONS: { [Key: string]: number } = {
    "CRIAR_CARDS": 1 << 0,
    "MOVER_CARDS": 1 << 1,
    "DELETAR_CARDS": 1 << 2,
    "EDITAR_CARDS": 1 << 3,
    "CRIAR_COLUNAS": 1 << 4,
    "MOVER_COLUNAS": 1 << 5,
    "DELETAR_COLUNAS": 1 << 6,
    "EDITAR_COLUNAS": 1 << 7,
    "CRIAR_DASHBOARDS": 1 << 8,
    "DELETAR_DASHBOARDS": 1 << 9,
    "EDITAR_DASHBOARDS": 1 << 10,
    "CRIAR_CHECKLISTS": 1 << 11,
    "DELETAR_CHECKLISTS": 1 << 12,
    "EDITAR_CHECKLISTS": 1 << 13,
    "CRIAR_PRAZOS": 1 << 14,
    "DELETAR_PRAZOS": 1 << 15,
    "EDITAR_PRAZOS": 1 << 16,
    "CRIAR_COMENTÁRIOS": 1 << 17,
    "EDITAR_COMENTÁRIOS_PRÓPRIOS": 1 << 18,
    "EDITAR_COMENTÁRIOS_EXTERNOS": 1 << 19,
    "DELETAR_COMENTÁRIOS_PRÓPRIOS": 1 << 20,
    "DELETAR_COMENTÁRIOS_EXTERNOS": 1 << 21,
    "RECEBER_NOTIFICAÇÕES_DE_SISTEMA": 1 << 22,
    "RECEBER_NOTIFICAÇÕES_PUSH": 1 << 23,
    "CONVIDAR_PARA_O_KANBAN": 1 << 24,
    "RETIRAR_DO_KANBAN": 1 << 25,
    "CRIAR_TAG": 1 << 26,
    "EDITAR_TAG": 1 << 27,
    "DELETAR_TAG": 1 << 28,
    "CRIAR_CAMPO": 1 << 29,
    "DELETAR_CAMPO": 1 << 30,
}

export const SYSTEM_PERMISSIONS_BOOLEAN: { [Key: string]: boolean } = {
    "CRIAR_CARDS": false,                       //  //
    "MOVER_CARDS": false,                       //
    "DELETAR_CARDS": false,                     //
    "EDITAR_CARDS": false,                      //
    "CRIAR_COLUNAS": false,                     //  //
    "MOVER_COLUNAS": false,                     //  //
    "DELETAR_COLUNAS": false,                   //  //
    "EDITAR_COLUNAS": false,                    //  //
    "CRIAR_DASHBOARDS": false,                  //  //
    "DELETAR_DASHBOARDS": false,                //  //
    "EDITAR_DASHBOARDS": false,
    "CRIAR_CHECKLISTS": false,                  //
    "DELETAR_CHECKLISTS": false,                //
    "EDITAR_CHECKLISTS": false,                 //
    "CRIAR_PRAZOS": false,                      //
    "DELETAR_PRAZOS": false,
    "EDITAR_PRAZOS": false,
    "CRIAR_COMENTÁRIOS": false,
    "EDITAR_COMENTÁRIOS_PRÓPRIOS": false,
    "EDITAR_COMENTÁRIOS_EXTERNOS": false,
    "DELETAR_COMENTÁRIOS_PRÓPRIOS": false,
    "DELETAR_COMENTÁRIOS_EXTERNOS": false,
    "RECEBER_NOTIFICAÇÕES_DE_SISTEMA": false,
    "RECEBER_NOTIFICAÇÕES_PUSH": false,
    "CONVIDAR_PARA_O_KANBAN": false,
    "RETIRAR_DO_KANBAN": false,
    "CRIAR_TAG": false,                         //
    "EDITAR_TAG": false,
    "DELETAR_TAG": false,
    "CRIAR_CAMPO": false,                       //
    "DELETAR_CAMPO": false,
}

export const PERMISSIONS_LIST: string[] = [
    "CRIAR_CARDS", "MOVER_CARDS", "DELETAR_CARDS", "EDITAR_CARDS", "CRIAR_COLUNAS", "MOVER_COLUNAS", "DELETAR_COLUNAS", "EDITAR_COLUNAS", "CRIAR_DASHBOARDS", "DELETAR_DASHBOARDS", "EDITAR_DASHBOARDS", "CRIAR_CHECKLISTS", "DELETAR_CHECKLISTS", "EDITAR_CHECKLISTS", "CRIAR_PRAZOS", "DELETAR_PRAZOS", "EDITAR_PRAZOS", "CRIAR_COMENTÁRIOS", "EDITAR_COMENTÁRIOS_PRÓPRIOS", "EDITAR_COMENTÁRIOS_EXTERNOS", "DELETAR_COMENTÁRIOS_PRÓPRIOS", "DELETAR_COMENTÁRIOS_EXTERNOS", "RECEBER_NOTIFICAÇÕES_DE_SISTEMA", "RECEBER_NOTIFICAÇÕES_PUSH", "CONVIDAR_PARA_O_KANBAN", "RETIRAR_DO_KANBAN", "CRIAR_TAG", "EDITAR_TAG", "DELETAR_TAG", "CRIAR_CAMPO", "DELETAR_CAMPO",
]

export const NATIONALITIES_ARRAY: string[] = [ "AF", "ZA", "AL", "DE", "AD", "AO", "AG", "SA", "DZ", "AR", "AM", "AU", "AT", "AZ", "BS", "BD", "BB", "BH", "BY", "BE", "BZ", "BJ", "BO", "BA", "BW", "BR", "BN", "BG", "BF", "BI", "BT", "CV", "CM", "KH", "CA", "QA", "KZ", "TD", "CL", "CN", "CY", "CO", "KM", "CG", "CI", "CR", "HR", "CU", "DK", "DJ", "DM", "EG", "SV", "AE", "EC", "ER", "SK", "SI", "ES", "US", "EE", "SZ", "ET", "FJ", "PH", "FI", "FR", "GA", "GM", "GH", "GE", "GD", "GR", "GT", "GY", "GN", "GQ", "GW", "HT", "NL", "HN", "HU", "YE", "MH", "SB", "IN", "ID", "IR", "IQ", "IE", "IS", "IL", "IT", "JM", "JP", "JO", "KI", "KW", "LA", "LS", "LV", "LB", "LR", "LY", "LI", "LT", "LU", "MK", "MG", "MY", "MW", "MV", "ML", "MT", "MA", "MU", "MR", "MX", "MM", "FM", "MZ", "MD", "MC", "MN", "ME", "NA", "NR", "NP", "NI", "NE", "NG", "NO", "NZ", "OM", "PW", "PA", "PG", "PK", "PY", "PE", "PL", "PT", "KE", "KG", "GB", "CF", "KR", "CD", "DO", "KP", "CZ", "RO", "RW", "RU", "WS", "SM", "LC", "KN", "ST", "VC", "SC", "SN", "SL", "RS", "SG", "SY", "SO", "LK", "SD", "SS", "SE", "CH", "SR", "TJ", "TH", "TZ", "TL", "TG", "TO", "TT", "TN", "TM", "TR", "TV", "UA", "UG", "UY", "UZ", "VU", "VE", "VN", "ZM", "ZW" ]

export const NATIONALITIES_CHECK_MAP: {[Key: string]: boolean} = {
    "AF": false,
    "ZA": false,
    "AL": false,
    "DE": false,
    "AD": false,
    "AO": false,
    "AG": false,
    "SA": false,
    "DZ": false,
    "AR": false,
    "AM": false,
    "AU": false,
    "AT": false,
    "AZ": false,
    "BS": false,
    "BD": false,
    "BB": false,
    "BH": false,
    "BY": false,
    "BE": false,
    "BZ": false,
    "BJ": false,
    "BO": false,
    "BA": false,
    "BW": false,
    "BR": false,
    "BN": false,
    "BG": false,
    "BF": false,
    "BI": false,
    "BT": false,
    "CV": false,
    "CM": false,
    "KH": false,
    "CA": false,
    "QA": false,
    "KZ": false,
    "TD": false,
    "CL": false,
    "CN": false,
    "CY": false,
    "CO": false,
    "KM": false,
    "CG": false,
    "CI": false,
    "CR": false,
    "HR": false,
    "CU": false,
    "DK": false,
    "DJ": false,
    "DM": false,
    "EG": false,
    "SV": false,
    "AE": false,
    "EC": false,
    "ER": false,
    "SK": false,
    "SI": false,
    "ES": false,
    "US": false,
    "EE": false,
    "SZ": false,
    "ET": false,
    "FJ": false,
    "PH": false,
    "FI": false,
    "FR": false,
    "GA": false,
    "GM": false,
    "GH": false,
    "GE": false,
    "GD": false,
    "GR": false,
    "GT": false,
    "GY": false,
    "GN": false,
    "GQ": false,
    "GW": false,
    "HT": false,
    "NL": false,
    "HN": false,
    "HU": false,
    "YE": false,
    "MH": false,
    "SB": false,
    "IN": false,
    "ID": false,
    "IR": false,
    "IQ": false,
    "IE": false,
    "IS": false,
    "IL": false,
    "IT": false,
    "JM": false,
    "JP": false,
    "JO": false,
    "KI": false,
    "KW": false,
    "LA": false,
    "LS": false,
    "LV": false,
    "LB": false,
    "LR": false,
    "LY": false,
    "LI": false,
    "LT": false,
    "LU": false,
    "MK": false,
    "MG": false,
    "MY": false,
    "MW": false,
    "MV": false,
    "ML": false,
    "MT": false,
    "MA": false,
    "MU": false,
    "MR": false,
    "MX": false,
    "MM": false,
    "FM": false,
    "MZ": false,
    "MD": false,
    "MC": false,
    "MN": false,
    "ME": false,
    "NA": false,
    "NR": false,
    "NP": false,
    "NI": false,
    "NE": false,
    "NG": false,
    "NO": false,
    "NZ": false,
    "OM": false,
    "PW": false,
    "PA": false,
    "PG": false,
    "PK": false,
    "PY": false,
    "PE": false,
    "PL": false,
    "PT": false,
    "KE": false,
    "KG": false,
    "GB": false,
    "CF": false,
    "KR": false,
    "CD": false,
    "DO": false,
    "KP": false,
    "CZ": false,
    "RO": false,
    "RW": false,
    "RU": false,
    "WS": false,
    "SM": false,
    "LC": false,
    "KN": false,
    "ST": false,
    "VC": false,
    "SC": false,
    "SN": false,
    "SL": false,
    "RS": false,
    "SG": false,
    "SY": false,
    "SO": false,
    "LK": false,
    "SD": false,
    "SS": false,
    "SE": false,
    "CH": false,
    "SR": false,
    "TJ": false,
    "TH": false,
    "TZ": false,
    "TL": false,
    "TG": false,
    "TO": false,
    "TT": false,
    "TN": false,
    "TM": false,
    "TR": false,
    "TV": false,
    "UA": false,
    "UG": false,
    "UY": false,
    "UZ": false,
    "VU": false,
    "VE": false,
    "VN": false,
    "ZM": false,
    "ZW": false,
}
